server:
  port: 8081

urlConsume: http://${micro-logistic}:8082/invoice

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host}:5432/db_invoice
    username: postgres
    password: admin